FROM dpage/pgadmin4:6.14


ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=pass
EXPOSE 80


#docker run --name mydba --network mynetwork -p 8081:80 -d my_dba 
# -p ports
# -v volume
# -e env